# Site settings
title: Do Phuc Hao
SEOTitle: Do Phuc Hao | Blog
header-img: img/about-bg.jpg
email: haodp.sut@gmail.com
description: "Let's do something amazing today!"
keyword: "Do Phuc Hao, @haodp, Do Phuc Hao Blog"
url: "dophuchao.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
#github_username:    dophuchao
#twitter_username:   HaoPDo1
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: dophuchao

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "PhD student"
sidebar-avatar: https://ibb.co/d6gzHR8 # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Site Google",
        href: "https://sites.google.com/view/dophuchao/"
    },{
        title: "Youtube",
        href: "https://www.youtube.com/c/%C4%90%E1%BB%97Ph%C3%BAcH%E1%BA%A3o"
    },{
        title: "GitHub",
        href: "https://github.com/dophuchao"
    },{
        title: "Medium",
        href: "https://medium.com/@haodp.sut"
    }, {
        title: "ORCID",
        href: "https://orcid.org/0000-0003-0645-0021"
    }
]
